name: Atualizar Playlist AngoStream

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  verificar-links:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: 📥 Baixar código
        uses: actions/checkout@v3
      
      - name: 🐍 Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: 📦 Instalar dependências
        run: |
          pip install requests
      
      - name: 🔍 Executar verificador
        run: |
          python scripts/check_links.py
      
      - name: 💾 Guardar alterações
        run: |
          git config --global user.name "Robô AngoStream"
          git config --global user.email "bot@angostream.ao"
          git add playlist_angostream.m3u
          git diff --quiet && git diff --staged --quiet || git commit -m "Atualização automática da playlist"
          git push
